### PR TITLE
Rebase upstream

### PR DESCRIPTION
**Pull request by cjrh**

### CODE REVIEW

**Comment by cjrh** [comment]
This is unfortunately quite messy.  We may want to just start again with a clean slate and redo our customizations on top of upstream head again.  Our custom filter code has to change for sure.

**Comment by wallies** [comment]
> This is unfortunately quite messy. We may want to just start again with a clean slate and redo our customizations on top of upstream head again. Our custom filter code has to change for sure.

What special things did we have the kapiche tokenizer, stat searcher and delete? Can we push any of these upstream? Or make them libs we pull into the build?

**Comment by cjrh** [comment]
I suspect we can't really.  Not sure, will have to look at it.

**Comment by cjrh** [comment]
Perhaps we can make our own library that wraps tantivy-py. If this is workable, it would make it much easier to keep up-to-date with upstream changes.  I'll take a look at this today.

**Comment by cjrh** [comment]
This approach is not going anywhere, closing.

**Pull request closed without merging**
